--- #YAML:1.0
name:                SWISH-API-Stat
version:             0.05
abstract:            reconnect to a SWISH::API handle if index file changes
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Path::Class::File::Stat:       0.02
    SWISH::API:                    0.04
    SWISH::API::More:              0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
