# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWISH-API-Stat
version:      0.04
version_from: lib/SWISH/API/Stat.pm
installdirs:  site
requires:
    Path::Class::File::Stat:       0.02
    SWISH::API:                    0.04
    SWISH::API::More:              0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
